@AirAwareApiHost = http://localhost:5077

### Get stored flights
GET {{AirAwareApiHost}}/api/Flights
Accept: application/json

### Sync active flights from AviationStack
POST {{AirAwareApiHost}}/api/Flights/sync
Accept: application/json
