// <auto-generated />
using System;
using AirAware.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirAware.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128183610_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirAware.Shared.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlightIata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginAirport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StressReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StressReportId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AirAware.Shared.StressReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaintenanceRecommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StressScore")
                        .HasColumnType("integer");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeedKph")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("StressReports");
                });

            modelBuilder.Entity("AirAware.Shared.Flight", b =>
                {
                    b.HasOne("AirAware.Shared.StressReport", "StressReport")
                        .WithMany()
                        .HasForeignKey("StressReportId");

                    b.Navigation("StressReport");
                });
#pragma warning restore 612, 618
        }
    }
}
