@AirAwareWeatherHost = http://localhost:5119

### Exercise the weather scoring logic
GET {{AirAwareWeatherHost}}/api/WeatherTest/analyze?airportCode=DXB&hours=9&locationName=Dubai%20International%20Airport
Accept: application/json
